Ты проснулся. Алилуя! Ты знаешь, СКОЛЬКО я ждал, пока твоё сознание удосужится посетить этот прекрасный мир иллюзий? Хотя это неважно: здесь понятия времени не существует впринципе, оно везде и нигде. Есть проблема гораздо важнее.

* 1. Где я?
В моей голове. Так уж вышло, что твоё сознание взяло власть над моим телом. Почти. Ты ничего не видишь, только слышишь. Я могу говорить только мысленно.

Проблема в том, что я нахожусь в твоём мире, сне. Но так как ты находишься во мне, ни о каком пробуждении речи не идёт. Пока я не найду то, что ищу – ты в вечной ловушке. 

Получается, что я твои глаза и уши, а ты — всё остальное. Неплохой обмен, правда?

Ужаснее некуда! Чтоб я сдох!

* 11. Как я здесь оказался?
* 12. Кто Я?
* 13. Опиши, где мы сейчас.

* 2. Кто ты?
Я собиратель сновидений. Странная профессия, но здесь вообще всё странное. У меня нет ни имени, эдакий ходячий сосуд. Я просто брожу по сновидениям других людей и собираю их ценные кусочки. Через них я пытаюсь собрать себя. Скучно, но другого выхода здесь нет. 

* 21. Опиши, где мы сейчас
Мы сейчас в твоём мире: сплошь бетонные платформе среди таких же бездонных платформ. Мегаструктуры, огромные и бессмысленные.

Я сижу у стены, не могу пошевелиться. Тело ноет, что странно: мне не нужна ни еда, ни вода, но боль всё равно ощущаю. Впереди виден край платформы. Сделать пять шагов – и я полечу вниз так долго, что арендодатель Вселенной уже успеет мне пару кругов намотать.

* 211. Что значит МОЙ мир?
Твой внутренний мир. Обычно они довольно небольшие и наполнены чем-то приятным или ужасным. Это значит, что у человека внутри что-то да есть. А в тебе пусто. Слишком пусто. Словно ни о чём не мечтаешь.

Передо мной край платформы. Пару шагов. Слева – дверь, через которую я попал сюда. Справа стена.

* 2111. Пошли налево
* 2112. Пошли вперёд
Свхинулся?! Слишком высоко, я сейчас упаду! 

* 999
Я понял одну вещь. Я – это Я, и никто другой. Мне больше не нужно собирать сновидения, плод чужой фантазии, потому что нашёл то, что так долго искал. Себя.
